## Copyright (c) 2024, 2026, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.
# spell-checker: ignore nindent

# ADB Wallet Password Secret
{{- if .Values.database }}
{{- if eq (include "obaas.database.isADBS" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-adb-wallet-pass-{{ .Release.Revision }}
  labels:
    app.kubernetes.io/component: database
    {{- include "obaas.labels" . | nindent 4 }}
stringData:
  {{ .Release.Name }}-adb-wallet-pass-{{ .Release.Revision }}: {{ include "obaas.randomPassword" . | quote }}
{{- end }}
{{- end }}
