
##
## Copyright (c) 2021 Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-dotnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
        version: dotnet
    spec:
      initContainers:
      - name: decode-creds
        command:
        - bash
        - -c
        - "for i in `ls -1 /tmp/creds | grep -v user_name`; do cat /tmp/creds/$i  | base64 --decode > /creds/$i; done; ls -l /creds/*;"
        image: oraclelinux:7.5
        volumeMounts:
        - name: creds-raw
          mountPath: /tmp/creds
          readOnly: false
        - name: creds
          mountPath: /creds
      containers:
      - name: inventory
        image: %DOCKER_REGISTRY%/inventory-dotnet:latest
        imagePullPolicy: Always
        env:
        - name: user
          value: "inventoryuser"
        - name: TNS_ADMIN
          value: "/msdataworkshop/creds"
        - name: inventoryqueuename
          value: "inventoryqueue"
        - name: OCI_REGION
          value: "%OCI_REGION%"
        - name: VAULT_SECRET_OCID
          value: "%VAULT_SECRET_OCID%"
        - name: dbpassword
          valueFrom:
            secretKeyRef:
              name: dbuser
              key: dbpassword
              optional: true #not needed/used if using VAULT_SECRET_OCID exists
        volumeMounts:
        - name: creds
          mountPath: /msdataworkshop/creds
        ports:
        - containerPort: 8080
      restartPolicy: Always
      volumes:
      - name: creds-raw
        secret:
          secretName: atp-demo-binding-inventory
      - name: creds
        emptyDir: {}
