apiVersion: apps/v1
kind: Deployment
metadata:
  name: supplier-helidon-se
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supplier
  template:
    metadata:
      labels:
        app: supplier
        version: helidon-se
    spec:
      initContainers:
      - name: decode-creds
        command:
        - bash
        - -c
        - "for i in `ls -1 /tmp/creds | grep -v user_name`; do cat /tmp/creds/$i  | base64 --decode > /creds/$i; done; ls -l /creds/*;"
        image: oraclelinux:7.5
        volumeMounts:
        - name: creds-raw
          mountPath: /tmp/creds
          readOnly: false
        - name: creds
          mountPath: /creds
      containers:
      - name: supplier
        image: %DOCKER_REGISTRY%/supplier-helidon-se:0.1
        imagePullPolicy: Always
        env:
        - name: database.user
          value: "INVENTORYUSER"
        - name: database.url
          value: "jdbc:oracle:thin:@%INVENTORY_PDB_NAME%_tp?TNS_ADMIN=/msdataworkshop/creds"
        - name: inventoryqueuename
          value: "inventoryqueue"
        - name: OCI_REGION
          value: "%OCI_REGION%"
        - name: VAULT_SECRET_OCID
          value: "%VAULT_SECRET_OCID%"
        volumeMounts:
        - name: creds
          mountPath: /msdataworkshop/creds
        ports:
        - containerPort: 8080
      restartPolicy: Always
      volumes:
      - name: creds-raw
        secret:
          secretName: atp-demo-binding-inventory
      - name: creds
        emptyDir: {}
