## Copyright (c) 2024, 2025, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.
apiVersion: v2
type: application
name: obaas-sample-app
description: A Helm chart for deploying applications to the Oracle Backend for Microservices and AI (OBaaS) Platform
home: https://oracle.github.io/microservices-datadriven
maintainers:
  - name: Oracle and/or its affiliates
    email: obaas_ww@oracle.com
    url: https://oracle.github.io/microservices-datadriven
version: 0.0.1
appVersion: "0.0.1"
