baseURL = 'https://oracle.github.io/microservices-datadriven/mbaas/'
languageCode = 'en-us'
title = 'Oracle Mobile Backend as a Service'
theme = "hugo-geekdoc"

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

# menu configuration
[params]
  geekdocMenuBundle = true
  
# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
   tag = "tags"