## Copyright (c) 2024, 2026, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-observability-config
  namespace: {{ .Release.Namespace }}
data:
  {{- if .Values.signoz.enabled }}
  signoz-otel-collector: http://{{ .Release.Name }}-signoz-otel-collector.{{ .Release.Namespace }}.svc.cluster.local:4318
  {{- end }}