  server:
    features:
      eureka:
        enabled: true
        client:
          base-uri: ${eureka.client.service-url.defaultZone}
          connect-timeout: PT10S
          read-timeout: PT30S
        instance:
          name: "customer-helidon"
          hostname: ${eureka.instance.hostname}
          prefer-ip-address: ${eureka.instance.preferIpAddress:true}

  otel:
    sdk:
      disabled: false
    service:
      name: ${OTEL_SERVICE_NAME:customer-helidon}
    exporter:
      otlp:
        endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}
        protocol: ${OTEL_EXPORTER_OTLP_PROTOCOL:http/protobuf}