## Copyright (c) 2024, 2026, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.
{{- if (index .Values "admin-server").enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-admin-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-admin-server
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: {{ .Release.Name }}
    {{- include "obaas.labels" . | nindent 4 }}
spec:
  replicas: {{ (index .Values "admin-server").replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-admin-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-admin-server
        app.kubernetes.io/component: backend
      {{- if .Values.signoz.enabled }}
      annotations:
        signoz.io/scrape: "true"
        signoz.io/port: "8989"
        signoz.io/path: "/actuator/prometheus"
      {{- end }}
    spec:
      {{- include "obaas.imagePullSecrets" (dict "local" (index .Values "admin-server").imagePullSecrets "global" .Values.global.imagePullSecrets) | nindent 6 }}
      containers:
      - name: admin-server
        image: "{{ (index .Values "admin-server").image.repository }}:{{ (index .Values "admin-server").image.tag }}"
        imagePullPolicy: {{ (index .Values "admin-server").image.pullPolicy | default "IfNotPresent" }}
        ports:
        - name: http
          containerPort: 8989
          protocol: TCP
        env:
        {{- if .Values.eureka.enabled }}
        - name: EUREKA_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-eureka-server
              key: url
        {{- end }}
        {{- if .Values.signoz.enabled }}
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://{{ .Release.Name }}-signoz-otel-collector.{{ .Release.Namespace }}:4318"
        {{- end }}
        resources:
          {{- if (index .Values "admin-server").resources }}
          {{- toYaml (index .Values "admin-server").resources | nindent 10 }}
          {{- else }}
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
          {{- end }}
{{- end }}
