## Copyright (c) 2024, 2026, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.
{{- if (index .Values "admin-server").enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-admin-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-admin-server
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: {{ .Release.Name }}
    {{- include "obaas.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8989
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-admin-server
{{- end }}
