version: "2.0.0"
registrySecrets:
  ocir:
    host: phx.ocir.io
    username: someone
    password: something
    email: someone@host.com
  ocr:
    host: container-registry.oracle.com
    username: someone
    password: something
    email: someone@host.com
clusterName: default
deploymentEnvironment: obaas
imagePullSecrets: []
eureka:
  enabled: true
  namespace: eureka
  imagePullSecrets: []
  image: obaas-docker-release.dockerhub-iad.oci.oraclecorp.com/eureka:1.4.0
apisix:
  enabled: true
  namespace: apisix
  imagePullSecrets: []
  image: docker.io/apache/apisix:3.11.0-debian
  busybox:
    image: docker.io/busybox:1.36
  dashboard:
    image: docker.io/apache/apisix-dashboard:3.0.0-alpine
    secret-namespace: ""
    secret-name: ""
  etcd:
    image: docker.io/bitnami/etcd:3.5.10-debian-11-r2
  yq:
    image: docker.io/linuxserver/yq:3.4.3
kafka:
  enabled: true
  namespace: kafka
  imagePullSecrets: []
  images:
    3-8-0: quay.io/strimzi/kafka:0.45.1-kafka-3.8.0
    3-8-1: quay.io/strimzi/kafka:0.45.1-kafka-3.8.1
    3-9-0: quay.io/strimzi/kafka:0.45.1-kafka-3.9.0
    3-9-1: quay.io/strimzi/kafka:0.45.1-kafka-3.9.1
  operator:
    image: quay.io/strimzi/operator:0.45.1
  bridge:
    image: quay.io/strimzi/kafka-bridge:0.31.2
  kaniko-executor:
    image: quay.io/strimzi/kaniko-executor:0.45.1
  maven-builder:
    image: quay.io/strimzi/maven-builder:0.45.1
coherence:
  enabled: true
  namespace: coherence
  imagePullSecrets: []
  image: container-registry.oracle.com/middleware/coherence-ce:25.03.1
  operator:
    image: container-registry.oracle.com/middleware/coherence-operator:3.5.2
admin-server:
  enabled: true
  namespace: admin-server
  imagePullSecrets: []
  image: obaas-docker-release.dockerhub-iad.oci.oraclecorp.com/admin-server:1.4.0
azn-server:
  enabled: true
  namespace: azn-server
  imagePullSecrets: []
  image: obaas-docker-release.dockerhub-iad.oci.oraclecorp.com/azn-server:1.4.0
signoz:
  namespace: observability
applicationNamespace:
  create: true
  name: application
database:
  # -- Either SIDB-FREE, ADB-FREE, or ADB-S
  type: "ADB-S"
  imagePullSecrets: []
  namespace: oracle-database-operator-system
  image: container-registry.oracle.com/database/adb-free:latest-23ai
  # -- For ADB-S, OCID of the Autonomous Database
  # Exclude for SIDB-FREE/ADB-FREE
  oci_db:
    # -- OCID of the DB
    ocid: "ocid1.autonomousdatabase.oc1.ap-mumbai-1.anrg6ljrq33dybyayf32tbbjrximdjvw4tlxahkzy7l4bo4ugfmejsaaqyea"
  adminUserAuthn:
    secretName: "admin-user-authn"
    # -- Namespace of Secret containing the authentication/connection details
    secretNamespace: "default"
    # -- Key in secretName containing the username
    usernameKey: "username"
    # -- Key in secretName containing the password
    passwordKey: "password"
    # -- Key in secretName containing the connection service name
    serviceKey: "service"
  podAnnotations: []
  podLabels: []
  # -- Oracle Cloud Infrastructure Configuration
  oci_config:
    keySecretName: "oci-config-file"
    ociConfigMapName: "oci-config"
  
    
