server:
  port : 8080

spring:
  applications:
    name: okafka-producer
  profiles:
    active: kubernetes
  cloud:
    kubernetes:
      reload:
        enabled: true
        mode: POLLING
        period: 2000
      config:
        name: okafka-producer-config
        namespace: lab

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
    restart:
      enabled: true
    info:
      enabled: true

logging:
  level:
    root: INFO
    org:
      springframework: INFO
    com:
      oracle:
        developers:
          eventmesh:
            teq:
              okafka: INFO

okafka-server-config:
  oracle-instance-name: lab8022_tp
  oracle-service-name: bsenjiat5lmurtq_lab8022_tp.adb.oraclecloud.com
  oracle-net-tns_admin: /home/appuser/wallet
  tns-alias: lab8022_tp
  security-protocol: SSL
  bootstrap-servers: adb.us-ashburn-1.oraclecloud.com:1522

okafka-topic-config:
  topic-name: LAB8022_TOPIC
  num-of-partitions: 3
  replication-factor: 1

okafka-producer-config:
  key-serializer-class: org.oracle.okafka.common.serialization.StringSerializer
  value-serializer-class: org.oracle.okafka.common.serialization.StringSerializer
  compression-type: snappy
  acks: all
  batch-size: 200
  batch-size-boost-factor: 100
  linger-ms: 100
  request-timeout-ms: 60000
  retry-count: 5
  buffer-memory: 335544