## Copyright (c) 2024, 2026, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.
{{- if and (index .Values "oracle-database-exporter").enabled (and $.Values.database $.Values.database.enabled) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-db-exporter-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-oracle-database-exporter
    app.kubernetes.io/component: metrics-exporter
    app.kubernetes.io/part-of: {{ .Release.Name }}
    {{- include "obaas.labels" . | nindent 4 }}
data:
  exporter-config.yaml: |2-

    # Example Oracle Database Metrics Exporter Configuration file.
    # Environment variables of the form ${VAR_NAME} will be expanded.

    databases:
      ## Path on which metrics will be served
      # metricsPath: /metrics
      ## Database connection information for the "default" database.
      default:
        ## Database username
        username: ${DB_USERNAME}
        ## Database password
        password: ${DB_PASSWORD}
        ## Database connection url
        url: ${DB_CONNECT_STRING}

        ## Metrics query timeout for this database, in seconds
        queryTimeout: 20

        ## Rely on Oracle Database External Authentication by network or OS
        # externalAuth: false
        ## Database role
        # role: SYSDBA
        ## Path to Oracle Database wallet, if using wallet
        tnsAdmin: ${TNS_ADMIN}

        ### Connection settings:
        ### Either the go-sql or Oracle Database connection pool may be used.
        ### To use the Oracle Database connection pool over the go-sql connection pool,
        ### set maxIdleConns to zero and configure the pool* settings.

        ### Connection pooling settings for the go-sql connection pool
        ## Max open connections for this database using go-sql connection pool
        maxOpenConns: 10
        ## Max idle connections for this database using go-sql connection pool
        maxIdleConns: 10

        ### Connection pooling settings for the Oracle Database connection pool
        ## Oracle Database connection pool increment.
        # poolIncrement: 1
        ## Oracle Database Connection pool maximum size
        # poolMaxConnections: 15
        ## Oracle Database Connection pool minimum size
        # poolMinConnections: 15

    metrics:
      ## How often to scrape metrics. If not provided, metrics will be scraped on request.
      # scrapeInterval: 15s
      ## Path to default metrics file.
      default: default-metrics.toml
      ## Paths to any custom metrics files
      # custom:
      #   - /oracle/observability/txeventq-metrics.toml

    log:
      # Path of log file
      destination: /log/alert.log
      # Interval of log updates
      interval: 15s
      ## Set disable to 1 to disable logging
      # disable: 0
{{- end }}
