## Copyright (c) 2024, 2025, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.

# CloudBank Account Service - Helm Values
#
# Install with (from this directory):
#   helm install account ../../../helm/charts/obaas-sample-app -f values.yaml -n <namespace>
#
# Upgrade with:
#   helm upgrade account ../../../helm/charts/obaas-sample-app -f values.yaml -n <namespace>
#
# Uninstall with:
#   helm uninstall account -n <namespace>

# -----------------------
# -- Required Configuration
fullnameOverride: "account"

image:
  repository: ""  # e.g., us-phoenix-1.ocir.io/mytenancy/cloudbank-v5/account
  tag: ""         # e.g., 0.0.1-SNAPSHOT

obaas:
  releaseName: "" # OBaaS platform release name (run: helm list -n <obaas-namespace>)
  framework: "SPRING_BOOT"

database:
  aq:
    enabled: true  # Account uses AQ for messaging


# -----------------------
# -- Feature Toggles

eureka:
  enabled: true

otel:
  enabled: true

otmm:
  enabled: true   # LRA participant

# imagePullSecrets:
#   - name: ocir
