## Copyright (c) 2024, 2026, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.
{{- if .Values.eureka.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-eureka
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-eureka
    app.kubernetes.io/component: service-discovery
    app.kubernetes.io/part-of: {{ .Release.Name }}
    {{- include "obaas.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 8761
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-eureka
{{- end }}
