
##
## Copyright (c) 2021 Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-helidon-se
  labels:
    app: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
        version: helidon-se
    spec:
      initContainers:
        - name: decode-creds
          command:
            - bash
            - -c
            - "for i in `ls -1 /tmp/creds | grep -v user_name`; do cat /tmp/creds/$i  | base64 --decode > /creds/$i; done; ls -l /creds/*;"
          image: oraclelinux:7.5
          volumeMounts:
            - name: creds-raw
              mountPath: /tmp/creds
              readOnly: false
            - name: creds
              mountPath: /creds
      containers:
        - name: inventory
          imagePullPolicy: Always
          image: %DOCKER_REGISTRY%/%IMAGE_NAME%:%IMAGE_VERSION%
          volumeMounts:
            - name: creds
              mountPath: /msdataworkshop/creds
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
            timeoutSeconds: 5
            failureThreshold: 20
          env:
            - name: LOG_LEVEL
              value: "DEBUG"
            - name: server_port
              value: "8080"
            - name: db_user
              value: "inventoryuser"
            - name: db_url
              value: "jdbc:oracle:thin:@%INVENTORY_PDB_NAME%_tp?TNS_ADMIN=/msdataworkshop/creds"
            - name: db_queueOwner
              value: "inventoryuser"
            - name: db_orderQueueName
              value: "orderqueue"
            - name: db_inventoryQueueName
              value: "inventoryqueue"
            - name: OCI_REGION
              value: "%OCI_REGION%"
            - name: VAULT_SECRET_OCID
              value: "%VAULT_SECRET_OCID%"
      restartPolicy: Always
      volumes:
        - name: creds-raw
          secret:
            secretName: atp-demo-binding-inventory
        - name: creds
          emptyDir: {}
