apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grabdish-grafana-ingress
  namespace: msdataworkshop
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    #nginx.ingress.kubernetes.io/backend-protocol: "https"
    #nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    #nginx.ingress.kubernetes.io/add-base-url: "true"
spec:
  tls:
    - secretName: ssl-certificate-secret
  rules:
    - https:
        paths:
          - path: /
#            pathType: Prefix
            pathType: ImplementationSpecific
            backend:
              service:
                name: grafana
                port:
#                  number: 80
                  number: 443