## Copyright (c) 2024, 2026, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.
{{- if (index .Values "otmm").enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-otmm-tcs
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-otmm-tcs
    app.kubernetes.io/component: transaction-coordinator
    app.kubernetes.io/part-of: {{ .Release.Name }}
    {{- include "obaas.labels" . | nindent 4 }}
spec:
  replicas: {{ (index .Values "otmm").replicas }}
  serviceName: {{ .Release.Name }}-otmm-tcs
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-otmm-tcs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-otmm-tcs
        app.kubernetes.io/component: transaction-coordinator
      {{- if .Values.signoz.enabled }}
      annotations:
        signoz.io/scrape: "true"
        signoz.io/port: "9000"
        signoz.io/path: "/metrics"
      {{- end }}
    spec:
      {{- include "obaas.imagePullSecrets" (dict "local" (index .Values "otmm").imagePullSecrets "global" .Values.global.imagePullSecrets) | nindent 6 }}
      serviceAccountName: {{ .Release.Name }}-otmm-tcs
      securityContext:
        runAsUser: 1000
      containers:
      - name: otmm-tcs
        image: "{{ (index .Values "otmm").image.repository }}:{{ (index .Values "otmm").image.tag }}"
        imagePullPolicy: {{ (index .Values "otmm").image.pullPolicy | default "IfNotPresent" }}
        ports:
        - name: http
          containerPort: 9000
          protocol: TCP
        env:
        - name: GIN_MODE
          value: release
        - name: CONFIG_MAP_PATH
          value: /etc/config
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        resources:
          {{- if (index .Values "otmm").resources }}
          {{- toYaml (index .Values "otmm").resources | nindent 10 }}
          {{- else }}
          limits:
            cpu: 250m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 1Gi
          {{- end }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Release.Name }}-otmm-config
{{- end }}
