## Copyright (c) 2024, 2026, Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v1.0 as shown at http://oss.oracle.com/licenses/upl.
apiVersion: v2
type: application
name: "obaas-prereqs"
kubeVersion: ">= 1.32.1"
description: Prerequisites and cluster-singleton infrastructure for Oracle Backend as a Service
home: https://oracle.github.io/microservices-datadriven
maintainers:
  - name: Oracle and/or its affiliates
    email: obaas_ww@oracle.com
    url: https://oracle.github.io/microservices-datadriven
# This is the chart version.
version: 0.0.1
# This is the version number of the application being deployed.
appVersion: "2.0.0"

# SubCharts - Cluster-scoped singleton infrastructure
dependencies:
  - name: external-secrets
    version: "1.1.0"
    repository: https://charts.external-secrets.io
    condition: external-secrets.enabled
  - name: metrics-server
    version: "3.13.0"
    repository: https://kubernetes-sigs.github.io/metrics-server/
    condition: metrics-server.enabled
  - name: kube-state-metrics
    version: "6.4.1"
    repository: https://prometheus-community.github.io/helm-charts
    condition: kube-state-metrics.enabled
  - name: strimzi-kafka-operator
    version: "0.45.1"
    repository: https://strimzi.io/charts/
    condition: strimzi-kafka-operator.enabled
  - name: oracle-database-operator
    # NOTE: cert-manager is a dependency of oracle-database-operator
    #       if cert-manager is already installed, modify values.yaml
    version: "0.1.0"
    repository: "file://charts"
    condition: oracle-database-operator.enabled
  - name: coherence-operator
    version: "3.5.6"
    repository: https://oracle.github.io/coherence-operator/charts
    condition: coherence-operator.enabled
