
##
## Copyright (c) 2021 Oracle and/or its affiliates.
## Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-helidon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
        version: helidon-mp
    spec:
      initContainers:
      - name: decode-creds
        command:
        - bash
        - -c
        - "for i in `ls -1 /tmp/creds | grep -v user_name`; do cat /tmp/creds/$i  | base64 --decode > /creds/$i; done; ls -l /creds/*;"
        image: oraclelinux:7.5
        volumeMounts:
        - name: creds-raw
          mountPath: /tmp/creds
          readOnly: false
        - name: creds
          mountPath: /creds
      containers:
      - name: order
        image: %DOCKER_REGISTRY%/order-helidon:0.1
        imagePullPolicy: Always
        env:
        - name: oracle.ucp.jdbc.PoolDataSource.orderpdb.user
          value: "ORDERUSER"
        - name: oracle.ucp.jdbc.PoolDataSource.orderpdb.URL
          value: "jdbc:oracle:thin:@%ORDER_PDB_NAME%_tp?TNS_ADMIN=/msdataworkshop/creds"
        - name: orderqueuename
          value: "orderqueue"
        - name: inventoryqueuename
          value: "inventoryqueue"
        - name: OCI_REGION
          value: "%OCI_REGION%"
        - name: VAULT_SECRET_OCID
          value: "%VAULT_SECRET_OCID%"
        - name: dbpassword
          valueFrom:
            secretKeyRef:
              name: dbuser
              key: dbpassword
              optional: true #not needed/used if using VAULT_SECRET_OCID exists
        volumeMounts:
        - name: creds
          mountPath: /msdataworkshop/creds
        ports:
        - containerPort: 8080
# Helidon/OKE health liveness/readiness
        livenessProbe:
          httpGet: #alternatives include exec with command, etc.
            path: /health/live
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 3
      restartPolicy: Always
      volumes:
      - name: creds-raw
        secret:
          secretName: atp-demo-binding-order
      - name: creds
        emptyDir: {}
